#!/bin/bash

container_id=$(sudo docker container ls | grep discordhort | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
	sudo docker container stop $container_id
fi
sudo docker image rm --force discordhort
sudo docker build -t discordhort .
sudo docker run -d -v db_discordhort:/app discordhort
